# Generated by Django 3.0.1 on 2020-01-30 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('displaying_name', models.CharField(max_length=200)),
                ('sorting_key', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AttributeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('displaying_name', models.CharField(max_length=200)),
                ('sorting_key', models.IntegerField()),
                ('type_name', models.CharField(max_length=200)),
                ('data_format', models.CharField(blank=True, max_length=200, null=True)),
                ('a_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='main.AttributeCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Category')),
            ],
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('a_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_values', to='main.AttributeType')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='main.Product')),
            ],
        ),
        migrations.AddField(
            model_name='attributecategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_categories', to='main.Category'),
        ),
    ]
