# Generated by Django 3.0.1 on 2020-01-27 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='attributefloat',
            name='a_type',
        ),
        migrations.RemoveField(
            model_name='attributefloat',
            name='product',
        ),
        migrations.RemoveField(
            model_name='attributeint',
            name='a_type',
        ),
        migrations.RemoveField(
            model_name='attributeint',
            name='product',
        ),
        migrations.AddField(
            model_name='attributetype',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Category'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AttributeChar',
        ),
        migrations.DeleteModel(
            name='AttributeFloat',
        ),
        migrations.DeleteModel(
            name='AttributeInt',
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='a_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_values', to='main.AttributeType'),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='main.Product'),
        ),
    ]
